# Generated by Django 4.2.16 on 2024-12-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=200)),
                ('stock', models.IntegerField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo')),
            ],
        ),
    ]
